import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/controls/OrbitControls.js';

// La pantalla de inicio debe responder incluso si alguna foto tarda en cargar.
const introEl = document.querySelector('#intro');
const enterBtn = document.querySelector('#enter');
if (enterBtn && introEl) {
  enterBtn.addEventListener('click', () => {
    introEl.classList.add('hidden');
    setTimeout(() => { introEl.style.display = 'none'; }, 900);
  });
}
const container=document.querySelector('#scene');const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x090011,.018);const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,200);camera.position.set(0,0,23);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);container.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.05;controls.minDistance=6;controls.maxDistance=42;controls.enablePan=false;
const galaxy=new THREE.Group(), photosG=new THREE.Group(), heartG=new THREE.Group();scene.add(galaxy,photosG,heartG);heartG.visible=false;
// stars
const starGeo=new THREE.BufferGeometry(), n=1800, pos=new Float32Array(n*3), col=new Float32Array(n*3);for(let i=0;i<n;i++){let r=4+Math.random()*35,a=Math.random()*Math.PI*2,z=(Math.random()-.5)*12;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=Math.sin(a)*r*.55;pos[i*3+2]=z;let c=new THREE.Color().setHSL(.72+Math.random()*.14,.8,.55+Math.random()*.3);col.set([c.r,c.g,c.b],i*3)}starGeo.setAttribute('position',new THREE.BufferAttribute(pos,3));starGeo.setAttribute('color',new THREE.BufferAttribute(col,3));galaxy.add(new THREE.Points(starGeo,new THREE.PointsMaterial({size:.09,vertexColors:true,transparent:true,opacity:.9})));
const spiralGeo=new THREE.BufferGeometry(), m=2400, sp=new Float32Array(m*3), sc=new Float32Array(m*3);for(let i=0;i<m;i++){let arm=i%3,r=Math.pow(Math.random(),.65)*20,a=arm*2.094+r*.8+(Math.random()-.5)*.8;sp[i*3]=Math.cos(a)*r;sp[i*3+1]=Math.sin(a)*r*.45;sp[i*3+2]=(Math.random()-.5)*(1.4+r*.08);let c=new THREE.Color().setHSL(.74+(Math.random()-.5)*.08,.85,.45+Math.random()*.3);sc.set([c.r,c.g,c.b],i*3)}spiralGeo.setAttribute('position',new THREE.BufferAttribute(sp,3));spiralGeo.setAttribute('color',new THREE.BufferAttribute(sc,3));galaxy.add(new THREE.Points(spiralGeo,new THREE.PointsMaterial({size:.055,vertexColors:true,transparent:true,opacity:.8})));
const love=['Te amo','Mi cielo','Mi princesa','Eres mi universo','Siempre tú','Mi persona favorita','Te adoro','Mi vida','Contigo todo','Qué suerte tenerte','Cielo bello','Para siempre'];
const sprites=[];function textSprite(text){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.font='700 34px Arial';x.textAlign='center';x.textBaseline='middle';x.shadowColor='#a64dff';x.shadowBlur=18;x.fillStyle='#f3dcff';x.fillText(text,256,64);const t=new THREE.CanvasTexture(c);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));s.scale.set(4.2,1.05,1);return s}
for(let i=0;i<love.length;i++){let s=textSprite(love[i]);let a=i/love.length*Math.PI*2;s.position.set(Math.cos(a)*10,Math.sin(a)*5,(Math.random()-.5)*8);scene.add(s);sprites.push(s)}
const photos=await fetch('photos.json').then(r=>{ if(!r.ok) throw new Error('No se pudo cargar photos.json'); return r.json(); }).catch(err=>{ console.error(err); return []; });const loader=new THREE.TextureLoader();const items=[];const total=photos.length;function heartPoint(t){let x=16*Math.pow(Math.sin(t),3),y=13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t);return new THREE.Vector3(x*.52,y*.52,0)}
photos.forEach((url,i)=>{loader.load(url,tex=>{tex.colorSpace=THREE.SRGBColorSpace;let ratio=tex.image.width/tex.image.height;const h=2.15,w=h*ratio;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide}));let a=i/total*Math.PI*2*3,r=5+(i%7)*1.45;let target=new THREE.Vector3(Math.cos(a)*r,Math.sin(a)*r*.52,(i%9-4)*1.2);mesh.position.copy(target);mesh.lookAt(0,0,0);photosG.add(mesh);let hp=heartPoint(i/total*Math.PI*2);hp.z=(i%5-2)*.25;items.push({mesh,galaxy:target,heart:hp});});});
let mode=0,transition=0;const heartBtn=document.querySelector('#heartBtn');heartBtn.onclick=()=>{mode=mode?0:1;document.body.classList.toggle('heart-mode',!!mode);heartBtn.textContent=mode?'🌌 Volver a galaxia':'❤️ Ver corazón';heartG.visible=false};
const loveEl=document.querySelector('#love');let li=0;setInterval(()=>{loveEl.textContent=love[li++%love.length]+' ✨'},2600);
function animate(){requestAnimationFrame(animate);controls.update();transition+=(mode-transition)*.035;items.forEach((o,i)=>{o.mesh.position.lerpVectors(o.galaxy,o.heart,transition);o.mesh.lookAt(camera.position)});sprites.forEach((s,i)=>{let p=1-transition;s.material.opacity=.2+.8*p;s.visible=p>.03});galaxy.rotation.z+=.0009*(1-transition);renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
